### ISSUE TITLE
Fix an issue with unhandled exception

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#107]
The following code causes an unhandled exception (and I suppose it should not):

```
Mata::Nfa::Nfa aut;
Mata::RE2Parser::create_nfa(&aut, "(a|b)*");
Mata::Nfa::Nfa aut2;
Mata::RE2Parser::create_nfa(&aut2, "(a|b)*b(a*)b");
Mata::Nfa::are_equivalent(aut, aut2);
```
Can you please fix it?

**Comment by Adda0** [comment]
Where? Give me the exception text and context. It passes just fine when I run this code as a test inside Mata.

**Comment by vhavlena** [comment]
```
due to unexpected exception with message:
  Trying to get minimum from sync. ex. iterator which has no minimum. Don't do
  that ever again or your nose falls off!
```

**Comment by vhavlena** [comment]
Sorry, my fault. This should be the code causing the exception:
```
Mata::Nfa::Nfa aut;
Mata::RE2Parser::create_nfa(&aut, "a*");
Mata::Nfa::Nfa aut2;
Mata::RE2Parser::create_nfa(&aut2, "(a|b)*");
Mata::Nfa::are_equivalent(aut, aut2);
```

**Comment by jurajsic** [comment]
I think this might be also a problem with the function `Mata::RE2Parser::create_nfa`, I am not sure if it correctly handles epsilon transitions. In Noodler we fixed it by removing epsilon transitions by our function implemented in Mata, but I am not sure if this solution was added to the main mata branch.

**Comment by kilohsakul** [comment]
fixed the bug in nfa-inclusion, fix is in a PR.

The issue of epsilon transitions noted by Juraj is not responsible for that bug, but also to be solved I guess.
