### ISSUE TITLE
Concatenation bug

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#112]
I have the following code:
```
Mata::Nfa::Nfa aut1;
Mata::RE2Parser::create_nfa(&aut1, "a*");
Mata::Nfa::Nfa aut2;
Mata::RE2Parser::create_nfa(&aut2, "b*");
Mata::Nfa::Nfa aut3;
Mata::RE2Parser::create_nfa(&aut3, "a*b*");
Mata::Nfa::are_equivalent(Mata::Nfa::concatenate(aut1, aut2), aut3);
```
The equivalence check on the last line should be true, but it is not. It seems there is a problem in concatenation resulting in this case to the NFA accepting "(a|b)*".

**Comment by kilohsakul** [comment]
How quickly do you need it fixed? I you need it quick I will do it if David cannot.

**Comment by vhavlena** [comment]
I don't need it immediately. But I guess it could possibly affect the work of @jurajsic Nevertheless we need to fix it in some reasonable time since it is a fundamental operation we use (I guess I can also fix it, maybe next week)

**Comment by martinhruska** [comment]
What's is the state of this issue? It's still not solved?

**Comment by Adda0** [comment]
It requires a more thorough rewrite of the concatenation algorithm. Work in progress, although the progress is seriously slow-going at the moment due to me not having time to rewrite the algorithm. Can be temporarily resolved by using concatenation with epsilon symbol set to true and removing epsilon symbols afterwards.

**Comment by martinhruska** [comment]
Ok, it's fine, I was just checking the status.

**Comment by vhavlena** [comment]
I suggest to use a simple concatenation with epsilons with subsequent removing of epsilons. I would not spend too much time with super-optimized implementation since we currently event don't know whether the concatenation is a real bottleneck.
