### ISSUE TITLE
Fix the broken binding in devel

### ISSUE THREAD

**Issue by tfiedor** [VeriFIT/mata#116]
Current binding is broken, because of the merge of one of the PRs.

Disclaimer: I won't be fixxing any binding in any PR until this issue is solved (in isolate PR).

Currently, I'm waiting for merging of the Data encapsulation, which had working binding, and contains some changes that could lead to some conflict if I started fixing this and also will be handy in fixing the break from #100. Once #101 is merged, I will try to fix it.

**Comment by tfiedor** [comment]
I will mention @martinhruska @kilohsakul so they are aware of this.

**Comment by martinhruska** [comment]
Well, I am afraid that #101 has broken binding as well.

**Comment by tfiedor** [comment]
No, before the merge of #100 the binding was fine, I fixed it in that PR. Your merge conflicts should not have broken the binding. As I said like 100 times, the binding is broken, because devel is broken. Even if you commited the documentation or code-unrelated changes, the binding will still be broken.

**Comment by martinhruska** [comment]
#100 is merged.

**Comment by tfiedor** [comment]
#108 #109 #115 should not break binding.

**Comment by tfiedor** [comment]
I will probably finish fixing the binding tomorrow.
