### ISSUE TITLE
Fix Mata CMake configuration

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#125]
The current CMake configuration should be modified and updated. Namely, the following should be done:
- add a definition of `install` command to easily install Mata on the system,
- create Mata CMake package which would allow using Mata in 3rd party projects with simple `find_package(proj mata*)` (*or `libmata`),
- fix Mata compilation process to correctly link with simlib,
-  fix how Mata includes 3rd party dependencies so that Mata can be seamlessly used as a submodule with simple `add_subdirectory` (which will compile the whole Mata with its 3rd party dependencies) and allow linking the whole compiled library with `target_link_libraries()`.

**Comment by martinhruska** [comment]
Solved by #131
