### ISSUE TITLE
Encapsulate Delta.post_size() wherever possible

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#127]
The library was so far based on determining number of states by checking size of post which is now implemented by method `Delta.post_size()`. Since we changed philosophy what number of states is we need to replace call to that method by `Nfa.max_state()`.

**Comment by martinhruska** [comment]
It looks that we want replace `post_size()` by `states_number` as proposed in issued #132.

**Comment by Adda0** [comment]
The issue #132 will be closed when the proposed method `Nfa::states_number()` is implemented. The encapsulation of the current uses of `Nfa::Delta::post_size()` is a requirement for closing this issue and will come in a separate PR.
