### ISSUE TITLE
Add method to get the current number of states in the automaton

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#132]
Similarly to `Nfa::max_state()`, we need a method to get the current number of states in initial states, final states, and in delta. Therefore, we should add a method `Nfa::states_number()` which would find max state (call `Nfa::max_state()`) and add one to include the state `0`. The method should look like the following:
```c++
    size_t states_number() const
    {
        return max_state() + 1;
    }
```

This function should be used everywhere instead of `Nfa::Delta::post_size()` when we are getting the current number of states in the whole automaton. As of now, `Nfa::Delta::post_size()` might not give a correct result.

**Comment by martinhruska** [comment]
I agree but `Nfa::states_number()` would be equivalent to `Nfa::Delta::post_size()` only when `delta[Nfa::max_state()]` is called before `Nfa::Delta::post_size()` it. Otherwise, `delta.post` does not need to be resized to `Nfa::max_state()`.

**Comment by vhavlena** [comment]
I agree with David. Currently a user not familiar with the internal structure of our NFA representation has no chance to get the number of states.

**Comment by Adda0** [comment]
> I agree with David. Currently a user not familiar with the internal structure of our NFA representation has no chance to get the number of states.

Not only would the user who is not familiar with the internal structure be confused, there is no correct way to get the current number of states in the whole automaton at all. Unless you call `Nfa::max_state() + 1` at all times. `Nfa::Delta::post_size()` will be correct in most of the cases, but not all of them.
