### ISSUE TITLE
Fix Nfa::defragment() and corresponding support functions

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#135]
`Nfa::defragment()` is broken. As of now, it defragments transition relation (not sure whether still correctly), but completely omits propagating the defragmentation changes to initial and final states and does not defragment initial and final state sets properly neither propagates their changes again.

We need to:
- [x] Verify that the defragmentation of transition relation is still sound.
- [x] Propagate the changes of Delta defragmentation. Namely,
  - [x] Rename initial and final states according to the defragmentation of Delta.
  - [x] Modify the `Nfa::m_states_number` member variable, perhaps.
- [x] Implement defragmentation of initial and final states, taking into account the remaining member variables (`m_states_number`, `initial`, `final`, `delta`) to keep them consistent with each other.

**Comment by martinhruska** [comment]
I thought a little bit about this problem. An elegant, but maybe not so efficient solution of this problem, would be

1. Defragment delta, get renaming map
2. Rename initial and finals accordingly
3. Defragment initals, get renaming map
4. Rename finals
5. Defragment finals
6. Change `m_states_number`.

It is definitely an easier way than composing different renaming maps together. However, the question is whether we want to sacrifice performance.

**Comment by Adda0** [comment]
I agree, let us do exactly what @martinhruska suggests right now. When we have a functioning implementation, we can further discuss how to optimize the process if there is a need. As of now, we need to have at least something working as intended.

**Comment by Adda0** [comment]
Resolved in #157.
