### ISSUE TITLE
Decide whether to keep Nfa::increase_size()

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#143]
```cpp
    //TODO: why this? Maybe we could have add_state(int state)
    //Btw, why do we need adding states actually, we could just add states with transitions, 
    // or with initial/final states.
    void increase_size(size_t size)
    {
        assert(this->delta.post_size() <= size);
        delta.increase_size(size);
    }
```
We should decide whether we want to keep `Nfa::increase_size()` or whether we want to modify the current function `Nfa::add_state()` to accept an argument specifying how many states to add (up to a state with internal representation equal to the passed parameter). If we decide to modify the `Nfa::add_state()` with a parameter, we can safely remove `Nfa::increase_size_for_state()` which would then do exactly the same as the updated `Nfa::add_state(State state)`.  

In addition, we should discuss whether we even want to have a function for adding individual states. I would say we do. We use the function `Nfa::add_state()` to add a sink state in some algorithms, for example. Or just to add a new state, which we will later use.

This issue aims to resolve TODOs in the above-shown code.

**Comment by martinhruska** [comment]
I'm suggest to add `Nfa::add_state(State )` and overload the method.
