### ISSUE TITLE
What should parameter `num_of_states` in Nfa constructor mean?

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#167]
Semantically, the most consistent behaviour would be for the constructor to only set the member variable `m_num_of_requested_states` and initialize an empty transition relation. However, there are two requirements for the constructor to fulfil.

First, when we construct an NFA with a known number of states from the start, we want to preallocate Delta immediately so that we do not have to resize Delta repeatedly when we add transitions one by one. This is based on how the number of states was interpreted in the past: the size of the transition relation represented the number of states in the automaton. Many algorithms were optimized with this in mind so that they preallocate (not prerequest: this is a fundamental difference) a certain number of states to optimize away the resize operations completely.

Second, correctly set the number of states somehow somewhere so that when we call `Nfa::Nfa::get_num_of_states()`, we get the same number of states.

Are both of these still valid? Do we want to change the current behaviour (preallocate `Delta`)? Do we want to add another method to preallocate Delta and optionally even methods to preallocate sets of initial and final states? What should be the default behaviour?

**Comment by martinhruska** [comment]
What about adding `Nfa` constructor with the params `maximal_state` and `delta_size`.  Then it would be obvious to a potential user that these things are different. The one param constructor `Nfa(maximal_state)` could stay there too.

**Comment by Adda0** [comment]
This is a great idea which would solve most of the issues, I believe. To be consistent with `Nfa(maximal_state, delta_size)`, `Nfa(n)` should only set the member variable `Nfa::m_num_of_requested_states` and do not allocate `Delta`.

**Comment by Adda0** [comment]
It was decided that constructor will allocate Delta, initial and final states. Add comment to explain which data structures are preallocated.

**Comment by Adda0** [comment]
Related to #189.

**Comment by kilohsakul** [comment]
I am now thinking about getting rid of all these numbers, to keep nfa simple, even for the price of some inconvenience. A state would be anything that is initial, final, or has a non-empty post. Then probably the only thing that would make sense in a constructor would be to reserve size of delta, initial, and final states.

**Comment by martinhruska** [comment]
There is a famous essay saying that it is slightly better to have simple implementation than logical consistency :-) But to be serious. The number of states variables are here for let say three months and it still feels unnatural for us. So maybe it's wrong since we haven't found the right way how to use it and I agree it makes sense to remove it and define state set as union of initial, final and non-empty posts.

**Comment by martinhruska** [comment]
anyway, is `m_num_of_requested_states` used yet in any algorithm?
