### ISSUE TITLE
true/false in mata format

### ISSUE THREAD

**Issue by jurajsic** [VeriFIT/mata#168]
Right now in the format there are two ways to write true/false: either `\true` and `\false` or `true` and `false`. We should decide which one we want to keep, right now we use the second one (`true` and `false`).
Also, why is there still `FORMAT.md` file?

**Comment by martinhruska** [comment]
We should also keep `true` and `false` consistent with `min` and `max` where `\` is also used.

**Comment by Adda0** [comment]
I think this question is general enough to be discussed in our meeting on Wednesday.

**Comment by jurajsic** [comment]
We agreed that we should use `\true` and `\false` instead of `true`/`false`. I think this issue should be solved together with #174.

**Comment by Adda0** [comment]
We agreed that #174 will be resolved as a separate issue.
