### ISSUE TITLE
Bug in determinize()

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#173]
The following test produces an assertion failure.

```cpp
        Nfa x{};
        x.initial.add(0);
        x.final.add(4);
        x.delta.add(0, 1, 3);
        x.delta.add(3, 1, 3);
        x.delta.add(3, 2, 3);
        x.delta.add(3, 0, 1);
        x.delta.add(1, 1, 1);
        x.delta.add(1, 2, 1);
        x.delta.add(1, 0, 2);
        x.delta.add(2, 0, 2);
        x.delta.add(2, 1, 2);
        x.delta.add(2, 2, 2);
        x.delta.add(2, 0, 4);
        OnTheFlyAlphabet alphabet{};
        auto complement_result{ determinize(x) };
```

**Comment by Adda0** [comment]
~~The problem seems to be that when we push back `Mata::Util::push_back(synchronized_iterator, aut.delta[q]);` an empty Post of `aut.delta[q]` (`q` has no transitions), the synchronized iterator advances with this empty post. The synchronized iterator takes this empty post and accesses its non-existent elements as if there was a transition to advance with. Thus advancing over the uninitialized memory and creating a current set of moves of type `{ <uninitialized_state>, <state> }`.~~

**Comment by Adda0** [comment]
Never mind. This is a much more serious error in Mata design. The problem lies in holding pointers to elements of a vector which is reallocated in the process, causing the pointers to be invalidated.

The root cause of the issue is that we allow Delta to not have allocated space for all automata states. When we access such unallocated state, we reallocate Delta and invalidate pointers even if, semantically, Delta does not change at all.

**Comment by kilohsakul** [comment]
Yes this needs to be solved systematically.

One solution: 
have two accessors, one, the original, returns a constant, the other one, with a different name, a non-constant for modifying. Like "delta.modifiable_moves(q)". When the delta of a state is not allocated, the constant accessor will return a reference to global constant variable with empty vector of moves. The accessor that returns a non-constant reference will allocate. Or it could return a pointer that could be null. 



Other possibilities, thoughts:
- we have only the accessor returning a constant, as above, and modifying is done through methods of delta, such as delta.add_transition(q,a,r). Don't know, looks like more work and more intreface in delta when compared to the possibility above. Ondra is using something like that in VATA, seems to work fine.

- have a function that allocates delta for all states in the automaton. User must call this to make sure that weirdness does not happen, I guess it would be called quite often. Kind of moronic.

- states of the automaton are those allocated in delta. But then adding an initial state which is not in delta does something weird, it adds it to the container of initial states but the automaton stays semantically the same. If the state is then added to delta, it is immediately initial ...

- everything is always allocated for all states of the automaton. All the structures, init, final, delta, have a pointer to the automaton to maintain this. Feels like a mess. Also adding that pointer for initial states probably means to make a class that  inherits from UnaryPredicate.

- put the accessors and modifier of initial, final, delta back to the automaton. Yes, over my dead body.
