### ISSUE TITLE
Constants (true/false) in FormulaNode

### ISSUE THREAD

**Issue by jurajsic** [VeriFIT/mata#174]
Currently the constants true/false are not represented in FormulaNode in any way and to check if it is there, we need to check for the name of the node. In #169 I added function is_constant(), is_true() and is_false(), but they also only check for the name of the node. Maybe we should add an option to enum of the node representing a constant operand true/false.

**Comment by martinhruska** [comment]
Agree, add it as an option to enum.

**Comment by jurajsic** [comment]
We will add true/false to enum. What is needed to be done:
1. Fix parsing from `.mata` format to `IntermediateAut` so that `\true`/`\false` (according to #168) is saved into node with correct option in enum.
2. Change functions `is_constant()`, `is_true()` and `is_false()` to check for the enum.
3. Check if we need to add checks for constants in current code whenever `IntermediateAut` is used. Probably in `Nfa::construct()`, `Afa::construct()` and in mintermization.

**Comment by Adda0** [comment]
@jurajsic What is the status of this issue? Considering we are revising the Mata file format, we should also have a look at this issue.

**Comment by jurajsic** [comment]
Haven't touched it at all.
