### ISSUE TITLE
Accepts epsilon function

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#178]
In string solving we need a function checking that an automaton accepts only epsilon (no other words). So far the workaround is that we minimize the automaton and then check the structure, which is obviously expensive. It would be nice to have a super-fast function for that in mata.

**Comment by martinhruska** [comment]
Removing all epsilon transitions from an initial to a final state and checking `is_lang_empty` is also too expensive?

**Comment by vhavlena** [comment]
I think it won't work. You want to check that the automaton accepts only a single word. One idea is to do trimming and then check if all initial states are final and have no successors.

**Comment by vhavlena** [comment]
I try to do something
