### ISSUE TITLE
Creating factory for specific types of automata 

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#188]
One small suggestion for discussion: I think this is one of the many cases of specific constructions of automata; I'm thinking if it might be useful to have specific namespace and file with these automata so they don't clog the space. E.g., `Mata::AutomataDatabase`, or `Mata::Factory`. This could have functions for creating: universal automata, single word automata, etc.

_Originally posted by @tfiedor in https://github.com/VeriFIT/mata/pull/185#pullrequestreview-1313947165_

**Comment by Adda0** [comment]
The idea of a factory sounds interesting. As of now, we have been struggling with deciding whether some specific type of automaton is a general enough that it should be in the `nfa.hh` interface or whether it should be a string solving only function.

**Comment by martinhruska** [comment]
yeah, it may be useful to add namespace `factory` or `builder` and don't pollute `nfa.hh` interface.

**Comment by martinhruska** [comment]
We should evolve this issue to redesign of library structure which we discussed at the last meeting. Maybe create a design dock or draft PR, where we can tinker with structure of library.

**Comment by tfiedor** [comment]
I think this should be linked to #262 , since the PR technically solves this issue. @Adda0 , please confirm.

**Comment by Adda0** [comment]
You are right. I was just waiting right until merging the PR before linking it to this issue, in case we decided to drop the commits creating the builder class and merge the PR without the changes requested in this issue. Right about now, it seems that no one has any objections to merging the PR with the builder class, so I can link this issue to the PR already. Thank you for notifying me.
