### ISSUE TITLE
Remove `Nfa::m_number_of_requested_states`

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#189]
It was decided that due to us not having any real use cases for `Nfa::m_number_of_requested_states` and the member variable being unnecessarily confusing, we will remove the member variable altogether.

As a consequence, the user will not be able to prerequest a certain number of states at the creation of an automaton or when calling `Nfa::Nfa::add_state()`.

**Comment by Adda0** [comment]
We need to discuss further how to manage creating new states. Currently, one can call `Nfa::Nfa::add_state()` to get a new state, even in a loop, and always get a new state (different value for each call). Do we want to preserve this functionality which is rather pleasant to work with, or do we force the user to handle this themselves?

**Comment by kilohsakul** [comment]
the m_num_requested_states and the similar thing in delta shuld probably be removed even if it takes some effort. It makes Nfa data structure much harder to work with. The thing in delta can particularly be removed assuming we define a state of an automaton as anything which is initial, final, or has an outgoing transitions (or has post).

**Comment by kilohsakul** [comment]
I will try to get rid of it, I want something to play with anyway.

**Comment by Adda0** [comment]
We decided to remove `m_number_of_states` from both `Mata::Nfa::Nfa` and `Mata::Nfa::Delta` classes.
