### ISSUE TITLE
Rename namespaces `Nfa` and `Afa` to mitigate name collisions?

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#204]
There is a suggestion to rename namespaces to, for example, `Mata::NFA` and `Mata::AFA`, to resolve name collisions with classes `Mata::Nfa::Nfa` and `Mata::Afa::Afa`. After that, we could use `using namespace Mata` and simultaneously `using namespace Mata::NFA`. Then we do not need to call `using Symbol = Mata::Symbol` and `using State = Mata::State` everywhere. And `Nfa` resolves to class `Nfa` and is not ambiguous: namespace `Nfa` or class `Nfa`?

**Comment by Adda0** [comment]
Still do not know.

**Comment by kilohsakul** [comment]
Namespaces with all letters capital? Including MATA and everything else.

**Comment by Adda0** [comment]
Definitely not all namespaces, but the few namespaces with conflicting names which represent an abbreviation anyway could use ALLCAPS format. That is, `NFA`, `AFA`, `SegNFA`, etc. This would solve the conflicts. `NFA::Nfa` looks good to me, too.

Alternatively, something like `Mata::Nfas::Nfa` could be used, but that is an inferior option to the all capital letters version.

**Comment by kilohsakul** [comment]
What was the reason for not having all namespaces starting with small letters? mata, nfa, delta, ...
I still like it in fact, simple, systematic, no fonclicts, immediately clear whether it is a namespace or a class, C++ uses it - e.g. std ... ?

**Comment by Adda0** [comment]
Some reasons to prefer namespace names starting with a capital letter:
- It is convention to name program-defined types starting with a capital letter. Using the same convention for program-defined namespaces is consistent (especially when using a qualified name such as Foo::x, where Foo could be a namespace or a class. 
- It helps prevent naming collisions with other system-provided or library-provided lower-cased names.
- The C++20 standards document uses this style.
- The C++ Core guidelines document uses this style.

Reasons copied from [LearnCpp article on user-defined namespaces](https://www.learncpp.com/cpp-tutorial/user-defined-namespaces-and-the-scope-resolution-operator/).

> C++ uses it - e.g. std ... 

No, system-level libraries and core language libraries use it in order to prevent intervening with user-lever namespaces. As explained by Bjarne Stroustrup:

> The C++ language and standard library don’t use capital letters, so it’s int rather than Int and string rather than String. That way, you can recognize the standard types.

Both approaches will compile, however. We can go for either.

The advantages of all lower-case namespaces are that there will be no conflicts with our implementations of classes inside these namespaces.

Anyone else any opinions on the topic?

**Comment by Adda0** [comment]
This issue was resolved in #309.
