### ISSUE TITLE
Rename strings to words

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#21]
There are multiple occurrences where words (as in, sequences of symbols) are addressed by *string*: in user defined types, function names, local variables etc.

It has been decided that, for the matter of consistency, all such occurrences should be renamed to *word*. Furthermore, *word* does not collide with C++ string type.

**Comment by martinhruska** [comment]
I am no longer sure that we want to do this. I've check where `word` and `string` are used and it makes sense to distinguish between them within library. `word` is used in context of finite automata as a word of language. On the other hand, `string` is used for the cases where a string (i.e., a sequence of characters) is parsed from input and translated to a number, e.g. symbol or state dictionary.

**Comment by Adda0** [comment]
You are right. This issue is no longer relevant, as all the original occurrences which I wanted to change were already fixed in the previous PRs or were otherwise modified. I am closing this issue now as fixed gradually over time.
