### ISSUE TITLE
RE to automata: desired behaviour?

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#22]
When playing with the python binding providing a translation of REs to automata, I encountered an issue probably with a symbol representation. For instance, I would expect that the RE "\xff" is translated to an automaton accepting a single letter "255". In fact, the translator creates an automaton accepting the word "195.191" (attached). Not really sure, if such a behaviour is indeed desired.
[aut3.dot.pdf](https://github.com/VeriFIT/toris/files/9118362/aut3.dot.pdf)

**Comment by tfiedor** [comment]
Does it work in the C++ library as expected? I guess, there is issue of encoding strings between python and c++ (currently, I'm encoding input strings to utf-8, but I guess you already encoded that in your string). I'm checking what the hell is going on.

**Comment by martinhruska** [comment]
I looks that there is a problem with unprintable characters. Try
`
    SECTION("Symbol encoding")
    {
        Vata2::Nfa::Nfa aut;
        Vata2::RE2Parser::create_nfa(&aut, "\x5a");
        aut.print_to_DOT(std::cout);
        REQUIRE(!aut.trans_empty());
        REQUIRE(!is_lang_empty(aut));
        REQUIRE(is_in_lang(aut, Word{'Z'}));
    }`

which works but
`
    SECTION("Symbol encoding")
    {
        Vata2::Nfa::Nfa aut;
        Vata2::RE2Parser::create_nfa(&aut, "\xff");
        aut.print_to_DOT(std::cout);
        REQUIRE(!aut.trans_empty());
        REQUIRE(!is_lang_empty(aut));
        REQUIRE(is_in_lang(aut, Word{255}));
    }`
does not work.
I need more time to inspect it.

**Comment by martinhruska** [comment]
Moreover, even if I escape `\` and it is successfully parsed I get the same bad result as Vojta:
```
    SECTION("Symbol encoding")
    {
        Vata2::Nfa::Nfa aut;
        Vata2::RE2Parser::create_nfa(&aut, "\\xff");
        aut.print_to_DOT(std::cout);
        REQUIRE(!aut.trans_empty());
        REQUIRE(!is_lang_empty(aut));
        REQUIRE(is_in_lang(aut, Word{255})); // THIS FAILS
    }
```

**Comment by martinhruska** [comment]
The problem is definitely on the side of the underlying C++ implementation.

**Comment by tfiedor** [comment]
OK, nevertheless, in next commit I will add `encoding='utf-8'` parameter to the function `from_regex` in python binding.

**Comment by martinhruska** [comment]
I think the problem is somehow related to the fact that 1) things with code higher than \x7f are not ascii; 2) and RE2 does not support unicode: https://github.com/google/re2/blob/main/doc/syntax.txt#L141. As an example of hex encoding they use \x7f https://github.com/google/re2/blob/main/doc/syntax.txt#L111, probably because they do not support higher codes. @vhavlena are you aware of this?

**Comment by vhavlena** [comment]
Actually, I was not aware of this. I need to check if it is a show-stopper (hopefully not). But there is still a fishy behaviour, for example for the RE ".*" (all characters). The automaton corresponding to this accepts similar strange sequences as in the example above. This RE is quite common, it should give some reasonable result.

**Comment by vhavlena** [comment]
Also according to RE2's wiki page it provides some Unicode character class names, so RE2 should be able to work with characters beyond ASCII at some level.

**Comment by martinhruska** [comment]
Yes, the automaton created for ".*" weird but the following test passes as expected:
```

    SECTION("Hex symbol encoding")
    {
        Vata2::Nfa::Nfa aut;
        Vata2::RE2Parser::create_nfa(&aut, "\\x7f");
        aut.print_to_DOT(std::cout);
        REQUIRE(!aut.trans_empty());
        REQUIRE(!is_lang_empty(aut));
        REQUIRE(is_in_lang(aut, Word{127}));
    }

    SECTION("Wild card")
    {
        Vata2::Nfa::Nfa aut;
        Vata2::RE2Parser::create_nfa(&aut, ".*");
        aut.print_to_DOT(std::cout);
        REQUIRE(!aut.trans_empty());
        REQUIRE(!is_lang_empty(aut));
        REQUIRE(is_in_lang(aut, Word{'w','h','a','t','e','v','e','r'}));
        REQUIRE(is_in_lang(aut, Word{127}));
        REQUIRE(is_in_lang(aut, Word{}));
        EnumAlphabet alph = { };
        REQUIRE(is_universal(aut,alph));
    }
```
The weirdnes may be a feature not a bug.

**Comment by vhavlena** [comment]
Ok then. It seems that if you want to avoid a mental breakdown, it is better to use ASCII only. Many thanks.

**Comment by martinhruska** [comment]
I'v checked their test cases and they use
1) unicode chars directly
https://github.com/google/re2/blob/5aec8b553863350e32d13bbf745eae81adcdce93/re2/testing/search_test.cc#L236
https://github.com/google/re2/blob/5aec8b553863350e32d13bbf745eae81adcdce93/re2/testing/filtered_re2_test.cc#L135
2) intervals are in ascii values:
https://github.com/google/re2/blob/6a994180b85293eafcce21d9f3eb8a3526498248/re2/testing/parse_test.cc#L102

**Comment by vhavlena** [comment]
Then it seems that a unicode character is represented in the automaton by the UTF-8 encoding using multiple bytes.

**Comment by martinhruska** [comment]
agree, it looks it works that way.

**Comment by martinhruska** [comment]
Ok, can we close this issue?

**Comment by vhavlena** [comment]
Yes
