### ISSUE TITLE
Rename to mata

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#23]
mata was chosen as a new name of this library. We need to:

- [X] 1. Rename the project
- [X] 2. Rename the namespaces in the source code
- [X] 3. Find any other occurences of vata2 in the project files and rename it.
- [x] 4. Hide `forked from ondrik/libvata2`. It is wanted by @kilohsakul, however I think that @ondrik will need to agree with this. I will contact github support which can remove the note about fork.

**Comment by ondrik** [comment]
> Hide forked from ondrik/libvata2. It is wanted by @kilohsakul, however I think that @ondrik will need to agree with this. I will contact github support which can remove the note about fork.

I don't care

**Comment by martinhruska** [comment]
This issue should be solved by pull request #24.

**Comment by martinhruska** [comment]
I've just contacted github support to detach this repository from the original one https://support.github.com/ticket/personal/0/1712379
