### ISSUE TITLE
Performance testing: Convert build system to CMake  

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#231]
We should convert the build system for performance testing and profiling to CMake for better maintainability and extensibility.

We need to:
- [x] Add support for switching between building debug and release versions of compiled binaries.
- [x] Be able to build separate binaries with specific configuration (some with release, some with debug and the same one with both release and debug configuration) by providing a workflow to build a single binary (whose source file is passed as an argument) and passing requested build options as parameters.
- [x] Make sure that all programs and templates in `tests-performance/` use the local implementation of Mata (user-level) rather than the version of Mata installed in the system (system-level). We want to be able to quickly test performance of the current build of Mata, not the stable installed version.
- [x] Convert build system using CMake and integrate it in the main CMake for the whole project to allow better compilation options and IDE integration for performance and profiling tests source files.
- [x] Fix running `make` in `tests-performance/src` to properly include `simlib` and `cudd` libraries.
- [x] Build performance and profiling tests in CI/CD using GitHub Actions.
- [x] Fix errors with some input automata.
- [x] Move template source files into folder `tests-performance/src/templates` so that they do not compile and are easily found.
- [x] Improve the perf testing guide to instruct the user to:
    - [x] copy one of the templates from `tests-performance/src/templates/` folder into the `tests-performance/src` under a new name (which will be the name of the new test binary after compilation) folder (do not forget to specify the importance of the correct target folder in the guide).
    - [x] Prepare an example of copying out one template, renaming the template, modifying the new test, compiling the test, run the test manually and with pycobench.
    - [x] Fix step 4: `as follows:` without any example following.
- [x] Add command `make test` (or similar) which will give some rudimentary results for performance testing.

**Comment by Adda0** [comment]
In addition, we need to make sure that all programs and templates in `tests-performance/` use the local implementation of Mata (user-level) rather than the version of Mata installed in the system (system-level). We want to be able to quickly test performance of the current build of Mata, not the stable installed version. This should be easy to resolve once we have a functioning CMake configuration for performance testing and some modifications in the source files.

**Comment by tfiedor** [comment]
Yes, that is good point.

**Comment by Adda0** [comment]
~~@tfiedor Could you verify that all the tasks marked as completed are resolved as of #316? Furthermore, if you think that the remaining tasks are resolved as well, could you mark them as such, too?~~

Resolved.
