### ISSUE TITLE
Move function definitions from header files to source files when possible

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#236]
When it is possible (and sensible), move source code for definitions of functions from header files to source code files.

**Comment by martinhruska** [comment]
What are some examples of functions definitions in header files? I can only think of implementation of some iterators.

**Comment by Adda0** [comment]
I do not know about anything specific. But I can image (and I think that is what @kilohsakul meant with this issue), that there are currently some random functions here and there in various header files, implemented maybe in a haste, and have been left in header files without any reason. I believe there still are some such functions and methods.

We should therefore go through all header files in the library and move implementation of functions into their respective source files.

**Comment by martinhruska** [comment]
Ok, some garbage collecting makes sense.
