### ISSUE TITLE
Missing automata operations

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#25]
I am starting an issue with useful automata operations that could be included to the library.

- `trim` removing redundant states (for some reason the regex translator generates many redundant states)
- `simulation-based minimization` reduction of nondeterministic automata

**Comment by martinhruska** [comment]
Lukas and @vhavlena  agreed that @Adda0 will implement the functions.

**Comment by Adda0** [comment]
As of now, `trim` was implemented in #36, `equivalence_check` and `concatenate` were implemented in #40.

The only function remaining yet unimplemented is `simulation-based minimization`.

**Comment by martinhruska** [comment]
The function `simulation-based minimization` was implemtend by #43 so we can close this issue.
