### ISSUE TITLE
Bug in parsing or mata output

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#259]
I exported an automaton (NFA) using `print_to_mata` and then I tried to load it. Unfortunately it is not working. It seems that it is caused by the header `NFA-explicit` used by `print_to_mata`. The parsing functions assume `NFA` I guess. The second thing is that if the input file contains empty line at the end, the parsing function stucks  in an infinite loop.

**Comment by Adda0** [comment]
Can you add a minimal example of the input you tried to parse and of the automaton you tried to print? With the examples, we can fix the bugs and add new tests to ensure the these cases are handled correctly in the future.

**Comment by vhavlena** [comment]
Yes, e.g.,
```
@NFA-explicit
%Alphabet-auto
%Initial q0
%Final q0
q0 0 q0
```
but I claim that every automaton obtained by `print_to_mata` is problematic.

**Comment by jurajsic** [comment]
You need to parse the result from the `print_to_mata()` in following way:
```
std::string automaton_in_mata_format = read_some_mata_file_created_using_print_to_mata();
// for parsing output of print_to_mata() we need to use IntAlphabet to get the same alphabet
IntAlphabet int_alph;
Nfa aut = construct(Mata::IntermediateAut::parse_from_mf(parse_mf(aut_big_mata))[0], &int_alph);
```
