### ISSUE TITLE
Implement parser for new automata format

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#26]
Once a format specification is complete, we will need support at least for NFA and AFA parsing.

**Comment by martinhruska** [comment]
NFA part is done.

**Comment by tfiedor** [comment]
@martinhruska was this addressed by some PR?

**Comment by martinhruska** [comment]
It is not complete yet. Parser is example/benchmark yet. It supports subset of Mata defined by its sets. We still need to implement things like transducers or intervals.
