### ISSUE TITLE
Proposal: Add codacy integration

### ISSUE THREAD

**Issue by tfiedor** [VeriFIT/mata#278]
I'm thinking if it would be handy to include codacy (see https://www.codacy.com/) integration to our GA/CI/CD. Codacy performs some static analysis checks for codebases (it should support C/C++).

I have been using it for Perun and it tracks for each PR "Code Quality", mainly in terms of security issues, potential bugs and even some performance/ineffectivity issues. It can be painful and annoying on the other hand (when you want to merge and there are some :x:), but in past it detected some bugs and security issues for me. The actual integration should be quite simple.

What do you think?

**Comment by tfiedor** [comment]
I tagged you all, this is low priority. Think about it.

**Comment by Adda0** [comment]
We agreed on trying Codacy out. If we find its warnings too intrusive, we can turn it off again.

**Comment by tfiedor** [comment]
Closing, as it is set up.
