### ISSUE TITLE
String variable NFA_TYPE defined in nfa.cc is empty.

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#3]
The string variable `NFA_TYPE` defined [here](https://github.com/VeriFIT/toris/blob/master/src/nfa/nfa.cc#L33) and declared [here](https://github.com/VeriFIT/toris/blob/master/include/vata2/nfa.hh#L37) is always empty when used later in code. I compile code with clang in the following version
```
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.4.0
Thread model: posix
```
The error leads to failures in unit tests 11,13,14,40, since the `NFA_TYPE` is used in virtual machine to register dispatcher for NFA and no dispatcher is found for NFA the string empty.

Any ideas what could be wrong with the implementation? 

P.S.:
I checked that the `NFA_TYPE` string is empty by adding the following print statment `std::cout << "HERE "<< Vata2::Nfa::TYPE_NFA;` to function `Vata2::Nfa::init` in the file `src/nfa-dispatch.cc`.

**Comment by ondrik** [comment]
Be careful, the init function is called before `main()` during initialization of static variables, in particular, the initialization of dispatchers starts happening [here](https://github.com/VeriFIT/toris/blob/devel/src/vm-dispatch.cc#L72), so correctness might depend on the order of linking and other fun stuff :-).

**Comment by ondrik** [comment]
Yes, it's ugly, but the other option was that the user needs to call it himself, or it could be done in [VM constructor](https://github.com/VeriFIT/toris/blob/devel/include/vata2/vm.hh#L188), which might actually not be so bad. In such a case, I would, however, consider changing the dispatching logic from being a global function into a method of VM.

**Comment by martinhruska** [comment]
Or we can just move the definition of `TYPE_NFA` (here)[https://github.com/VeriFIT/toris/blob/devel/src/vm-dispatch.cc#L11] to vm-dispatch.cc and everything works fine.

**Comment by ondrik** [comment]
I would discourage this, since it introduces stronger dependence between VM and NFA.

**Comment by martinhruska** [comment]
Since VM was removed, this issue is no longer relevant.
