### ISSUE TITLE
Bug in mintermising automata in tests-performance

### ISSUE THREAD

**Issue by kilohsakul** [VeriFIT/mata#302]
~~Bug in performance tests, mutliple automata are mintermised independently. They must be mintermised together.~~

Maybe also parsing of NFA, perhaps transitions ending in "true" state, or with "true" symbol ...
For instance aut52 has states q0-q14 but is parsed with states q0-q15, I think.

[https://github.com/VeriFIT/mata/blob/perf_test_ach_inclusion/tests-performance/src/ach-inclusion-hardcoded-hard.cc](https://github.com/VeriFIT/mata/blob/perf_test_ach_inclusion/tests-performance/src/ach-inclusion-hardcoded-hard.cc)

This example should produce some large intersection and give antichain inclusion a hard time.

**Comment by tfiedor** [comment]
@kilohsakul I have addressed first batch of issues in PR #305 : mintermization for `binary-operations` should now be done together not per automaton. I believe, this is only places, where the mintermization was not done together.

You mentioned some suspicions about alphabets that they might be isolate for each automaton, at first glance I do not see anything wrong in `tests-performance/` sources (unless I misunderstood some parts of mata) and this might be inherent issue of parser. I will investigate this further.

I will now focus on checking the issue you mention in your code. I also wonder if this might be related to #168 ?

**Comment by Adda0** [comment]
> Bug in performance tests, mutliple automata are mintermised independently. They must be mintermised together.

Fixed in #305.

**Comment by tfiedor** [comment]
This was resolved, I believe, closing.
