### ISSUE TITLE
Wrapper classes StatePost, and for initial and final states sets?

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#325]
Question originally raised in https://github.com/VeriFIT/mata/pull/277#discussion_r1281437136. 

> But `initial` and `final` can still have size(), right? since they are just sets.

They will have to be unless you want to create a wrapper class `SparseStateSet`. It would have a member `SparseSet`, method `num_of_states()` which would only call `return this->sparse_set.size();` and add the boilerplate code for all other functions unmodified, as what we intend to do for `StatePost`.

However, if we do this for `StatePost`, we could create the wrapper for sparse set, too. It is the same wrapper as `StatePost` is for `OrdVector<SymbolPost>`. Opinions?

**Comment by Adda0** [comment]
@kilohsakul @jurajsic @tfiedor @vhavlena Any opinions?

**Comment by kilohsakul** [comment]
I would probably not implement these wrappers. It is a lot of work and code and will only complicate the interface.

**Comment by jurajsic** [comment]
Would the wrapper be useful in some way? Because I don't really see it

**Comment by vhavlena** [comment]
I would keep the things as simple as possible. I see it as a complication, which is not so beneficial to me now.

**Comment by Adda0** [comment]
Unless we plan on somehow extending the wrappers in the future (with methods named specifically for states, etc.), the wrapper is useless in my opinion. The only advantage in the current stage would be getting a number of states would be consistent with `Delta` and `Nfa`.

**Comment by tfiedor** [comment]
Sadly, I don't really care about this.

**Comment by Adda0** [comment]
No one sees a reason for the wrappers. We will keep the types as they are now. I will close this issue as resolved, then.
