### ISSUE TITLE
Remove revert function.

### ISSUE THREAD

**Issue by martinhruska** [VeriFIT/mata#33]
Remove revert function which is redundant.

**Comment by Adda0** [comment]
`Nfa::invert()` and `Nfa::revert()` functions handle adding new states (if necessary) to the result automaton differently. We should decide which approach to use in the remaining `Nfa::invert()` function.

**Comment by Adda0** [comment]
> we should keep invert functino behaviour as it is - i.e., with addiing new states.

That is fine by me.

> What do you mean by new method? A member method of Nfa class? Why?

Yes, `Nfa::invert()` as a member method. Simply for convenience. I think calling `aut.invert()` is simpler for the user than `aut = invert(aut)`. Having this member method is not a necessity, though. I can get by without it.

**Comment by martinhruska** [comment]
Solved by PR #57
