### ISSUE TITLE
Self-concatenating for in-place concatenation

### ISSUE THREAD

**Issue by jurajsic** [VeriFIT/mata#349]
Calling `aut.concatenate(aut)` now breaks everything, we should fix that. Probably it is enough to copy only the original states (up to original `aut.num_of_states()`).

Also, we should fix that concatenation does not return trimmed automata if we give it trimmed automata. This could be done by checking whether some transition goes into initial states of the second automaton, if not, they are not copied into concatenation.

**Comment by vhavlena** [comment]
This should be fixed already.

**Comment by Adda0** [comment]
Should or is (minus unknown bugs)? Has anyone tried on at least some example?

**Comment by vhavlena** [comment]
As far as I remember, I have fixed it at some point and there should be some test for that.

**Comment by Adda0** [comment]
Great. I am closing this issue, then.
