### ISSUE TITLE
RE2 automaton construction

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#37]
When using the python binding for RE->NFA translation on the regular expression `((aa)*)*(b)*` I get the following error:
`libc++abi: terminating with uncaught exception of type std::out_of_range: 0 or 18446744073709551615 is not a state.`

**Comment by tfiedor** [comment]
Is this the behaviour of python binding only? Or this this fail for the original C++ code?

**Comment by tfiedor** [comment]
Yes, the issue, unfortunately, seems to be in the C++ implementation.

I reproduced the test in the https://github.com/VeriFIT/mata/tree/hotfix-regex-error branch.

**Comment by martinhruska** [comment]
I'm going to try to detect bug causing this problem.

**Comment by martinhruska** [comment]
I pushed a commit fixing the issue. However, it doesn't still work. The created automaton is incorrect:
`digraph finiteAutomaton {
node [shape=circle];
1 [shape=doublecircle];
2 [shape=doublecircle];
0 -> {3 } [label=97];
1 -> {1 2 } [label=98];
node [shape=none, label=""];
i1 -> 1;
}`

**Comment by martinhruska** [comment]
I sent a bug report to Michal Horky, the author of RE2 parser, on Friday. He has not responded yet, so I will wait for few days and eventually I will ping him again.

**Comment by martinhruska** [comment]
I've just pushed update by Michal Horky to hotfix branch, could you please check it out?

**Comment by martinhruska** [comment]
The issue is solved by PR #38
