### ISSUE TITLE
Add Python bindings for the new functions

### ISSUE THREAD

**Issue by Adda0** [VeriFIT/mata#42]
With PRs #36, #40 and #41, there are multiple new functions needing Python bindings. Once #41 is reviewed and merged, we need to implement Python bindings for the new functions these PRs introduce.

The new functions which require Python bindings are:
- [x] `Mata::Nfa::SegNfa::noodlify()`,
- [x] `Mata::Nfa::intersection()` (both implementations: classic and epsilon transitions preserving),
- [x] `Mata::Nfa::concatenate()`,
- [x] `Mata::Nfa::equivalence_check()` (both implementations),
- [x] `Mata::Nfa::Nfa::trim()`,
- [x] `Mata::Nfa::Nfa::get_useful_states()`,
- [x] `Mata::Nfa::Nfa::get_reachale_states()`,
- [x] `Mata::Nfa::Nfa::get_terminating_states()`,
- [x] `Mata::Nfa::Nfa::remove_epsilon()`,
- [x] `Mata::Nfa::SegNfa::Segmentation()` (new constructors),
- [x] `Mata::Nfa::SegNfa::Segmentation::get_epsilon_depths()`,
- [x] `Mata::Nfa::SegNfa::Segmentation::get_segments()`,
- [x] `Mata::Nfa::Nfa::get_transitions_from_state()`,
- [x] `Mata::Nfa::Nfa::get_transitions_to_state()`,
- [x] `Mata::Nfa::Nfa::get_trans_from_state_as_sequence()`,
- [x] `Mata::Nfa::Nfa::get_trans_as_sequence()`,
- [x] `Mata::Nfa::Nfa()` (both new constructors),
- [x] `Mata::Nfa::Nfa::get_digraph()`,
- [x] `Mata::Nfa::Nfa::make_final()` (add missing implementation for `make_final(states)`, similar to Python bindings `add_initial_state()` and `add_initial_states()`),
- [x] `Mata::Nfa::Nfa::clear_initial()`,
- [x] `Mata::Nfa::Nfa::clear_final()`,
- [x] `Mata::Nfa::Nfa::remove_initial()` (both implementations),
- [x] `Mata::Nfa::Nfa::remove_final()` (both implementations),
- [x] `Mata::Nfa::Nfa::reset_initial()` (both implementations),
- [x] `Mata::Nfa::Nfa::reset_final()` (both implementations),
- [x] `Mata::Nfa::Nfa::increase_size_for_state()`,
- [x] `Mata::Nfa::Nfa::remove_trans()` (both implementations).

**Comment by tfiedor** [comment]
Thanks, for listing the functions, it will help me a lot. Just for a record: why are some functions already checked out? You already implemented the binding somewhere?

P.S. Python allows only one constructor, so new constructors will not need to be implemented (or more precisely cannot be). Alternatively the constructor in the Python can be updated if there is some significant extentions in some of the new constructors.

**Comment by Adda0** [comment]
>  why are some functions already checked out? You already implemented the binding somewhere?

Yes, I have already implemented them. And I will continue implementing others. Every time I implement one, I check it here. If you could maybe do the same, we can both work on this issue together.

> P.S. Python allows only one constructor, so new constructors will not need to be implemented (or more precisely cannot be). Alternatively the constructor in the Python can be updated if there is some significant extentions in some of the new constructors.

There are two new constructors for `Mata::Nfa::Nfa` which allow creating a new NFA with some specific features of another NFA (the new NFA has the same initial and final states etc.). This behaviour could be implemented in Python with optional parameters for the current constructor, for example.

**Comment by tfiedor** [comment]
If you have some other work to do, you can leave the binding to me ;-), just push the branch to this repo, so I can update it. I would be cautious on working on the same file on the same branch.

As for the constructors, I will think about it after I see them, but I guess it could be implemented also as a class function.

**Comment by Adda0** [comment]
> If you have some other work to do, you can leave the binding to me ;-), just push the branch to this repo, so I can update it. I would be cautious on working on the same file on the same branch.

I can do that. Thank you. In the meantime, could you review #41? It would help me to know whether there is something needing changes.

> As for the constructors, I will think about it after I see them, but I guess it could be implemented also as a class function.

That would be a good approach, too, I think.

**Comment by tfiedor** [comment]
Yes, I'm in the middle of reviewing. If you want to do the binding, then do what you can, just leave the constructors to me and ping me when your done with your share and I will finish the rest.

**Comment by martinhruska** [comment]
Should be this issue closed by #44?
