### ISSUE TITLE
Bug in noodlification, specifically in simulation reduction

### ISSUE THREAD

**Issue by jurajsic** [VeriFIT/mata#427]
There seems to be some problem with reduction of the intersection automaton during noodlification, see [this commit](https://github.com/VeriFIT/mata/commit/ea68dc044967a3bf2b497d13593d237aff0c273c) for an example where this shows up.
The intersected automaton with epsilons should be simple line `q0 -0-> q1 -0-> q2 -eps-> q3 -0-> q4 -0-> q5` but for some reason, after reduction ([line 382](https://github.com/VeriFIT/mata/blob/ea68dc044967a3bf2b497d13593d237aff0c273c/src/strings/nfa-noodlification.cc#L382)), it turns into `q0 -0-> q1 -0-> q2 -eps-> q3` with self-loop on `q3` and NO final states.
Maybe the problem is that we are reducing and putting it into the same variable?

**Comment by Adda0** [comment]
I will have a look. Thank you for the bug report.
