### ISSUE TITLE
Killed when parsing file with an empty automaton

### ISSUE THREAD

**Issue by adastepkova** [VeriFIT/mata#436]
I am using the python binding, `libmata` version 1.6.9.

Running the following code results in the program being killed due to high memory consumption.
```
from libmata import alphabets, parser
alpha = alphabets.OnTheFlyAlphabet.from_symbol_map({})
mata_nfa = parser.from_mata("path/to/empty.mata", alpha)
```

The contents of the file are:
```
@NFA
%Alphabet 0 1
%Initial 
%Final 

```
The same happens for different alphabets.

**Comment by Adda0** [comment]
Thank you for reporting the issue. The issue should be now fixed in Mata 1.6.12. Please, let us know if you encounter this issue again.
