### ISSUE TITLE
Parsing trivial .mata files can coredump

### ISSUE THREAD

**Issue by jn1z** [VeriFIT/mata#443]
Example from nfa-bench/benchmarks/bool_comb/ere/password-sat-passw_sat4-aut18.mata

This file is pretty trivial, which is likely the problem:

@NFA-bits
%Initial q0
%Final

./build/examples/example05-parsing nfa-bench/benchmarks/bool_comb/ere/password-sat-passw_sat4-aut18.mata

parsing ../nfa-bench/./benchmarks/bool_comb/ere/password-sat-passw_sat4-aut18.mata
Intermediate automaton type NFA
Naming - state: 1 symbol: 1 node: 1
Alphabet 1
Initial states: 0 
Final states: 
Transitions: 

free(): invalid pointer
Aborted (core dumped)

**Comment by jn1z** [comment]
Possibly a dupe of https://github.com/VeriFIT/mata/issues/436

**Comment by Adda0** [comment]
Yes, that is a bug with our parser. Fixing at least the bugs related to the parser is on our roadmap in the near future. We will try to fix the issue with these simple examples first.

**Comment by Adda0** [comment]
Thank you for reporting the issue. The issue should be now fixed in Mata 1.6.12. Please, let us know if you encounter this issue again.
