### ISSUE TITLE
Possible overflow in regex parser

### ISSUE THREAD

**Issue by adastepkova** [VeriFIT/mata#456]
I am using the Python binding, libmata version 1.6.18.

When parsing the regex `[\x00-\x5a\x5c-\x7f]`, the resulting automaton has an edge under all numbers from 0 to 127, and also under numbers from 4294967264 to 4294967295. Also, there is an edge under 91 ('\x5b'), although it should be excluded.

Relevant code:

```
import libmata.parser as parser
from libmata.plotting import plot

regex = "[\\x00-\\x5a\\x5c-\\x7F]"
m_nfa = parser.from_regex(regex)
plot(m_nfa)
```

**Comment by Adda0** [comment]
Thank you for another great bug report. We will investigate.

**Comment by adastepkova** [comment]
Thanks! I have found that the same happens with ranges of the form `[\x00-XY-\x7f]`, where X is between \x5a and \x5f, Y is between \x5c and \x61, and the difference between X and Y is at least 2.
