### ISSUE TITLE
Python binding: "minimize" parameter in complement does not work

### ISSUE THREAD

**Issue by adastepkova** [VeriFIT/mata#458]
Running `complement` with "minimize" as "true" does not produce a minimized automaton.

Example:

```
import libmata.nfa.nfa as mata_nfa
from libmata import alphabets
alphabet = alphabets.OnTheFlyAlphabet.from_symbol_map({"a": 0})
nfa = ...
comp = mata_nfa.complement(nfa, alphabet, params={"algorithm": "classical", "minimize": "true"})
```

where `nfa` is 

```
initial_states: [0]
final_states: [0, 2]
transitions:
0-[0]→1
1-[0]→2
2-[0]→3
3-[0]→0
```

and `comp` is

```
initial_states: [0]
final_states: [1, 3]
transitions:
0-[0]→1
1-[0]→2
2-[0]→3
3-[0]→0
```

Running `minimize` after complementation produces the minimized automaton:

```
initial_states: [0]
final_states: [1]
transitions:
0-[0]→1
1-[0]→0
```

Also, running `mata_nfa.complement(nfa, alphabet, params={"minimize": "true"})` throws this error:
 `RuntimeError: complement requires setting the "algo" key in the "params" argument; received: {minimize -> true}`. But the key actually accepted by the function is "algorithm" instead of "algo".

**Comment by Adda0** [comment]
Thank you for such valuable bug reports. This is an issue with an inconsistent Python binding with our C++ interface. @koniksedy discovered that when we removed the `minimize` parameter from the C++ interface for this operation, we forgot to update the Python binding. We will update the binding interface later. For now, Just manually call minimization after the operation. I would close this issue when the Python binding documentation and interface is updated.

**Comment by Adda0** [comment]
We have updated the Python interface and thus we close this issue. Thank you once again for reporting it.
