### ISSUE TITLE
RE2 regex bug

### ISSUE THREAD

**Issue by vhavlena** [VeriFIT/mata#48]
When working with the regex parser (with python binding), I got the following fishy outcomes:
`mata.Nfa.from_regex("[qQrR]*")` yields
`initial_states: [0]
final_states: [0]
transitions:
0-[113]→0
0-[114]→0`

`mata.Nfa.from_regex("[qr]*")` yields the same automaton as before
`initial_states: [0]
final_states: [0]
transitions:
0-[113]→0
0-[114]→0`

**Comment by martinhruska** [comment]
@MichalHorky Could you please check the example? It looks that there is a bug.

**Comment by MichalHorky** [comment]
> @MichalHorky Could you please check the example? It looks that there is a bug.

Sure, I will look into it

**Comment by MichalHorky** [comment]
It should be solved in [re2_regex_bugfix](https://github.com/VeriFIT/mata/tree/re2_regex_bugfix) branch. Could you check it, please?

**Comment by vhavlena** [comment]
It seems it is working. Thanks a lot for the prompt fix

**Comment by martinhruska** [comment]
Ok, i'm gonna merge it to devel.

**Comment by martinhruska** [comment]
Closing issue with PR #50
