### ISSUE TITLE
Many type defs in nfa.hh

### ISSUE THREAD

**Issue by kilohsakul** [VeriFIT/mata#79]
There are many named types "using ... that and that".
nfa.hh looks kind of scary. 
My first guess is that it only makes the code harder to read, unles one memorises all of them. 
I remember that we started with about five of them originally, in order to be able to swap the std containers in the nfa trnsition function.
I don't see why the other ones are there right now, in case there are really there for no big reason, then I woul dbe for dumping them.

**Comment by martinhruska** [comment]
Another thing related to this issue is naming of things as @kilohsakul suggested in #77. That PR was postponed in favor of better one but we should discuss it.

**Comment by martinhruska** [comment]
This should be partially addressed by #88.
