### ISSUE TITLE
Resetting the version of mata (discussion)

### ISSUE THREAD

**Issue by tfiedor** [VeriFIT/mata#84]
Some, people complained, that it is strange to have 1.X.Y version of mata, since it is not finished.

Hence, I'm raising discussion, whether we should reset the version to 0.1.0, e.g. and continue with the clean state.

Technically, it should not be that hard.

**Comment by Adda0** [comment]
Both views have some valid points, in my opinion. I would be fine with either option. `0.1.X` could be better if we want to specify a time in the future when we say that the library is finished in its first major version and can be used by anyone as it is. Nevertheless, the same can be done with any other version. We will just not have that nice announcement “We are finally in the 1.0 release.” and the library is ready to be used.

All in all, I have no problems with the current version number, but I am OK with resetting to version `0.1.X`, too. Are there any other reasons to reset the version number?

**Comment by martinhruska** [comment]
I am for reset. It does not make sense to have version >1.00 when we don't even have fixed the main interfaces yet.

**Comment by tfiedor** [comment]
I've raised the issue, since some didn't like that we are already at 1.X.Y release. I for one have no strong opinion. (In perun we have 0.X.Y for more than 5 years; I just didn't feel like releasing 1.0.0 yet.) However, I see no strong consensus through other projects (some have 0.X.Y. for many years, some have 12.X.Y and so on). So it is purely on our own whims and tastes (or maybe mostly on Lukas's). Removing tags, packages, etc. is no problem.

**Comment by martinhruska** [comment]
I think we agreed that the version should be reset. Could it be implemented?

**Comment by tfiedor** [comment]
Yes, I will reset it soon. I had to first fix some issues with pip install (thanks to cooperation with Ondra, it should be working now)

**Comment by tfiedor** [comment]
Fixed by #126
