### ISSUE TITLE
Encapsulate transition relation to isolate class

### ISSUE THREAD

**Issue by kilohsakul** [VeriFIT/mata#85]
Maybe making classes for transition relation would be good after all. Lets try to discuss here.

The reason is that we actually will want to modify the data structures,
mainly to make extensions of the library. So far, it seems that we will want to:
- include counters
- include general registers
- have a version that mixes BDDs with automata - has binary alphabet and levels of states.

And we will probably want to be able to fine tune some data structures after all. Maybe not much and often, but it would be good to make it possible.

**Comment by martinhruska** [comment]
@kilohsakul is this solved by the current changes?
