### ISSUE TITLE
Some notes on the automata format

### ISSUE THREAD

**Issue by vojnar** [VeriFIT/mata#9]
A few comments on the automata format:

1. What is meant by the "shared nodes" in the format?
2. What transition does a single a symbol or interval represent?
3. (a) The description of the format mentions complemented intervals as something that is not so needed. Well, I would very much vote for having them. In my experience with ARMC, the complemented sets were VERY useful. 
    (b) The current format uses "^" in the negated intervals, which is not mentioned among the special symbols: add or use "!" instead (which is, however, not so common).
    (c) Also, I guess that classical sets of the form [abg-p] are not included since it is assumed that they would be replaced by multiple transitions. However, that stops working for negated sets: one cannot so easily encode things like [^abg-p]. Myself, I would vote for supporting classical sets as well as their negations (indeed, for many people writing something like [abc] or [^abc] is very usual).
4. How are initial states encoded?
5. Acceptance is done through transitions without a target state?
6. In the transducers:
    (a) The description uses the notation x@a1 (also used at the beginning of the document when describing the basic notation), but the example uses a1@x.
    (b) The example mixes symbols with tracks and without tracks. If a track is not specified, what does that mean?
7. What does the notation f"z=x" mean in the special transducer transitions? Can one use something like [a-z]"x=y" to say that the same symbol from [a-z] is read by both of the tracks?

**Comment by martinhruska** [comment]
My notes from today meeting:

1. Format is white space sensitive but this should not relate to formulas in transitions which could be written without whitespaces
2. {} will no be used for enclosing attributes, so they will not be needed as special symbols.
3. % will not be used as appendix of a transition
4. Better describe what min, max are
5. Keywords true, false, min, max should start with \, i.e., \true, \false, \min, \max
6. Better exeplain what epsilon formula is and why it is useful.

**Comment by martinhruska** [comment]
@kilohsakul or me should solve the notes above.

**Comment by Adda0** [comment]
Just some side notes from the meeting, maybe for future reference.
1. Possibly allow using functions such as `toUpper`, `toLower` etc.
2. Warn that one cannot use intervals for previously unspecified alphabet. It would cause a crash.
3. Possibly add an attribute `%Comment` as an alternative way of specifying comments beside `#`.

**Comment by kilohsakul** [comment]
Updated in the decription.
